import { Patient, Doctor, MedicalReport, AiAssessment } from '../types';

export const INITIAL_DOCTORS: Doctor[] = [
  {
    id: 'DOC-101',
    name: 'Dr. Arjun Rao',
    department: 'Cardiology',
    specialization: 'Interventional Cardiology',
    availability: 'Available',
    currentPatients: 1,
  },
  {
    id: 'DOC-102',
    name: 'Dr. Priya Sharma',
    department: 'Emergency',
    specialization: 'Emergency Medicine',
    availability: 'Available',
    currentPatients: 2,
  },
  {
    id: 'DOC-103',
    name: 'Dr. Rahul Verma',
    department: 'General Medicine',
    specialization: 'Internal Medicine',
    availability: 'Available',
    currentPatients: 0,
  },
  {
    id: 'DOC-104',
    name: 'Dr. Meena Reddy',
    department: 'Emergency',
    specialization: 'Critical Care & Resuscitation',
    availability: 'Busy',
    currentPatients: 4,
  },
  {
    id: 'DOC-105',
    name: 'Dr. Vikram Seth',
    department: 'Pulmonology',
    specialization: 'Respiratory Medicine',
    availability: 'Available',
    currentPatients: 1,
  },
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'P001',
    name: 'Sreeja Valluru',
    age: 18,
    gender: 'Female',
    phone: '9876502001',
    email: 'sreeja@example.com',
    bloodGroup: 'O+',
    department: 'Cardiology',
    status: 'STABLE',
    symptoms: ['Mild headache'],
    medicalHistory: ['None Reported'],
    emergencyContact: {
      name: 'Emergency Contact',
      relationship: 'Primary Contact',
      phone: '9876503001',
    },
    vitals: {
      heartRate: 78,
      bloodPressure: '120/80',
      systolicBP: 120,
      diastolicBP: 80,
      spO2: 98,
      temperature: 36.7,
      respiratoryRate: 16,
      bloodGlucose: 100,
      measuredAt: 'Recorded in Encounter',
    },
    clinicalRecords: [],
    reports: [],
    latestAssessment: undefined,
    assignedDoctor: 'Dr. Ananya Rao',
    assignedDoctorId: 1,
    treatmentStatus: 'ROUTINE',
    treatmentHistory: [],
    waitingTimeMinutes: 0,
    registeredAt: '2026-09-10',
  },
  {
    id: 'P002',
    name: 'Anita Sharma',
    age: 42,
    gender: 'Female',
    phone: '+91 98123 45678',
    bloodGroup: 'B+',
    department: 'General Medicine',
    status: 'HIGH',
    symptoms: ['Persistent Headache', 'Weakness', 'Elevated Blood Pressure', 'High Grade Fever'],
    medicalHistory: ['Asthma (Mild)', 'Hypothyroidism'],
    emergencyContact: {
      name: 'Ramesh Sharma',
      relationship: 'Husband',
      phone: '+91 98123 45679',
    },
    vitals: {
      heartRate: 110,
      bloodPressure: '145/95',
      systolicBP: 145,
      diastolicBP: 95,
      spO2: 91,
      temperature: 39.1,
      respiratoryRate: 24,
      bloodGlucose: 140,
      measuredAt: '20 mins ago',
    },
    clinicalRecords: [
      {
        id: 'CR-102',
        patientId: 'P002',
        visitDate: '2026-09-12 13:30',
        doctorName: 'Dr. Rahul Verma',
        heartRate: 110,
        bloodPressure: '145/95',
        spO2: 91,
        temperature: 39.1,
        chiefComplaint: 'Persistent headache for 2 days with high fever and severe weakness.',
        diagnosis: 'High Grade Pyrexia / Suspected Systemic Infection',
        notes: 'Antipyretics administered. Complete Blood Count and blood cultures ordered.',
      },
    ],
    reports: [
      {
        id: 'REP-504',
        patientId: 'P002',
        patientName: 'Anita Sharma',
        reportName: 'Complete Blood Count (CBC)',
        date: '2026-09-12 13:35',
        type: 'Blood Work',
        riskLevel: 'HIGH',
        status: 'Final',
        findings: 'Total WBC: 16,800/mcL (Ref 4,000-11,000), Neutrophils: 84%.',
        summary: 'Significant leukocytosis with neutrophilia indicating acute infection.',
        vitalsAtTest: { spO2: 91, temperature: 39.1 },
      },
    ],
    latestAssessment: {
      id: 'AI-902',
      patientId: 'P002',
      patientName: 'Anita Sharma',
      riskScore: 74,
      priority: 'HIGH',
      assessedAt: '2026-09-12 13:40',
      riskFactors: [
        'Moderate Hypoxia (SpO2 91%)',
        'High Fever (39.1°C)',
        'Elevated Systolic BP (145 mmHg)',
        'Tachypnea (RR 24 breaths/min)',
      ],
      explanation: 'High risk classified due to high pyrexia and respiratory acceleration. Prompt clinical review and antibiotic coverage recommended.',
      recommendedActions: [
        'Priority clinical evaluation and doctor assignment',
        'Initiate Antipyretic & IV hydration protocol',
        'Monitor SpO2 and body temperature every 30 mins',
      ],
      status: 'Active',
    },
    assignedDoctor: undefined,
    assignedDoctorId: undefined,
    treatmentStatus: 'WAITING',
    treatmentHistory: [],
    waitingTimeMinutes: 28,
    registeredAt: '2026-09-12 13:20',
  },
  {
    id: 'P003',
    name: 'Suresh Reddy',
    age: 67,
    gender: 'Male',
    phone: '+91 97654 32109',
    bloodGroup: 'A+',
    department: 'Emergency',
    status: 'MODERATE',
    symptoms: ['Mild Breathing Difficulty', 'Fatigue', 'Abdominal Discomfort'],
    medicalHistory: ['Gallstones', 'Osteoarthritis'],
    emergencyContact: {
      name: 'Kavitha Reddy',
      relationship: 'Daughter',
      phone: '+91 97654 32110',
    },
    vitals: {
      heartRate: 88,
      bloodPressure: '135/88',
      systolicBP: 135,
      diastolicBP: 88,
      spO2: 94,
      temperature: 37.8,
      respiratoryRate: 19,
      bloodGlucose: 125,
      measuredAt: '35 mins ago',
    },
    clinicalRecords: [
      {
        id: 'CR-103',
        patientId: 'P003',
        visitDate: '2026-09-12 13:00',
        doctorName: 'Dr. Priya Sharma',
        heartRate: 88,
        bloodPressure: '135/88',
        spO2: 94,
        temperature: 37.8,
        chiefComplaint: 'Abdominal tightness and exertion fatigue.',
        diagnosis: 'Mild Respiratory Exertion & Abdominal Discomfort',
        notes: 'Placed under clinical observation. Basic lab work initiated.',
      },
    ],
    reports: [
      {
        id: 'REP-505',
        patientId: 'P003',
        patientName: 'Suresh Reddy',
        reportName: 'Abdominal Ultrasound',
        date: '2026-09-12 13:15',
        type: 'Ultrasound',
        riskLevel: 'MODERATE',
        status: 'Final',
        findings: 'Distended gallbladder with mild wall thickening (3.8mm).',
        summary: 'Mild cholecystitis features without perforation.',
        vitalsAtTest: { heartRate: 88 },
      },
    ],
    latestAssessment: {
      id: 'AI-903',
      patientId: 'P003',
      patientName: 'Suresh Reddy',
      riskScore: 48,
      priority: 'MODERATE',
      assessedAt: '2026-09-12 13:20',
      riskFactors: [
        'Borderline Low SpO2 (94%)',
        'Slightly Elevated BP (135/88)',
        'Mild Fever (37.8°C)',
      ],
      explanation: 'Moderate risk assigned based on mild vital abnormalities and localized discomfort. Hemodynamically stable; emergency treatment queue not indicated.',
      recommendedActions: [
        'Clinical observation in secondary triage unit',
        'Review diagnostic reports upon completion',
        'Schedule follow-up evaluation if symptoms progress',
      ],
      medicationConsiderations: [
        {
          medication: 'Paracetamol 500mg',
          reason: 'Mild fever relief and symptomatic discomfort management.',
          caution: 'Verify liver function baseline prior to administration.',
          approvalRequired: true,
        },
        {
          medication: 'Antacid Gel 10mL',
          reason: 'Symptomatic relief for upper abdominal tightness.',
          caution: 'Ensure patient remains upright post intake.',
          approvalRequired: true,
        },
      ],
      status: 'Active',
    },
    assignedDoctor: undefined,
    assignedDoctorId: undefined,
    treatmentStatus: 'OBSERVATION',
    treatmentHistory: [],
    waitingTimeMinutes: 45,
    registeredAt: '2026-09-12 12:50',
  },
  {
    id: 'P004',
    name: 'Rahul Verma',
    age: 37,
    gender: 'Male',
    phone: '9876502004',
    email: 'rahul@example.com',
    bloodGroup: 'AB+',
    department: 'Cardiology',
    status: 'CRITICAL',
    symptoms: ['Severe chest pain'],
    medicalHistory: ['Coronary Artery Disease'],
    emergencyContact: {
      name: 'Emergency Contact',
      relationship: 'Primary Contact',
      phone: '9876503004',
    },
    vitals: {
      heartRate: 128,
      bloodPressure: '88/60',
      systolicBP: 88,
      diastolicBP: 60,
      spO2: 89,
      temperature: 38.5,
      respiratoryRate: 24,
      bloodGlucose: 110,
      measuredAt: 'Recorded in Encounter',
    },
    clinicalRecords: [],
    reports: [],
    latestAssessment: {
      id: 'AI-904',
      patientId: 'P004',
      patientName: 'Rahul Verma',
      riskScore: 100,
      priority: 'CRITICAL',
      assessedAt: new Date().toISOString(),
      riskFactors: ['Very high heart rate', 'Low systolic blood pressure', 'Very low oxygen saturation'],
      explanation: 'Risk assessment based on: Very high heart rate, Low systolic blood pressure, Very low oxygen saturation, Elevated respiratory rate, Severe symptom: Severe chest pain, Chest pain detected. This assessment is decision support and should be reviewed by a doctor.',
      recommendedActions: ['Immediate doctor review and treatment'],
      status: 'Active',
    },
    assignedDoctor: 'Dr. Ananya Rao',
    assignedDoctorId: 1,
    treatmentStatus: 'IN_PROGRESS',
    treatmentHistory: [],
    waitingTimeMinutes: 10,
    registeredAt: '2026-09-10',
  },
  {
    id: 'P005',
    name: 'Kiran Patel',
    age: 59,
    gender: 'Male',
    phone: '+91 94321 09876',
    bloodGroup: 'B-',
    department: 'Cardiology',
    status: 'HIGH',
    symptoms: ['Chest Discomfort', 'Fatigue', 'Irregular Heartbeat', 'Dizziness'],
    medicalHistory: ['Atrial Fibrillation', 'Hypertension'],
    emergencyContact: {
      name: 'Meena Patel',
      relationship: 'Wife',
      phone: '+91 94321 09877',
    },
    vitals: {
      heartRate: 142,
      bloodPressure: '160/100',
      systolicBP: 160,
      diastolicBP: 100,
      spO2: 90,
      temperature: 37.2,
      respiratoryRate: 22,
      bloodGlucose: 180,
      measuredAt: '15 mins ago',
    },
    clinicalRecords: [
      {
        id: 'CR-105',
        patientId: 'P005',
        visitDate: '2026-09-12 13:30',
        doctorName: 'Dr. Arjun Rao',
        heartRate: 142,
        bloodPressure: '160/100',
        spO2: 90,
        temperature: 37.2,
        chiefComplaint: 'Sudden onset rapid irregular heartbeat and lightheadedness.',
        diagnosis: 'Atrial Fibrillation with Rapid Ventricular Response (RVR)',
        notes: 'IV Rate control protocol initiated. Continuous cardiac telemetry.',
      },
    ],
    reports: [
      {
        id: 'REP-506',
        patientId: 'P005',
        patientName: 'Kiran Patel',
        reportName: 'Telemetry ECG Strip',
        date: '2026-09-12 13:40',
        type: 'ECG',
        riskLevel: 'HIGH',
        status: 'Final',
        findings: 'Irregularly irregular rhythm, absent p-waves, ventricular rate 142 bpm.',
        summary: 'Atrial Fibrillation with RVR.',
        vitalsAtTest: { heartRate: 142, bloodPressure: '160/100' },
      },
    ],
    latestAssessment: {
      id: 'AI-905',
      patientId: 'P005',
      patientName: 'Kiran Patel',
      riskScore: 68,
      priority: 'HIGH',
      assessedAt: '2026-09-12 13:45',
      riskFactors: [
        'Severe Tachycardia (142 bpm)',
        'Borderline Low SpO2 (90%)',
        'Elevated BP (160/100)',
        'Atrial Fibrillation RVR',
      ],
      explanation: 'High risk classified due to rapid ventricular response in AFib. Requires doctor assignment and prompt rate control intervention.',
      recommendedActions: [
        'Priority doctor assignment & cardiac consultation',
        'Continuous ECG & BP Monitoring',
        'Echocardiogram evaluation',
      ],
      status: 'Active',
    },
    assignedDoctor: undefined,
    assignedDoctorId: undefined,
    treatmentStatus: 'WAITING',
    treatmentHistory: [],
    waitingTimeMinutes: 20,
    registeredAt: '2026-09-12 13:10',
  },
  {
    id: 'P006',
    name: 'Deepa Nair',
    age: 48,
    gender: 'Female',
    phone: '+91 93210 98765',
    bloodGroup: 'A-',
    department: 'Pulmonology',
    status: 'CRITICAL',
    symptoms: ['Severe Respiratory Distress', 'Cyanosis', 'Wheezing'],
    medicalHistory: ['Severe Asthma', 'COPD Overlap'],
    emergencyContact: {
      name: 'Gopal Nair',
      relationship: 'Brother',
      phone: '+91 93210 98766',
    },
    vitals: {
      heartRate: 130,
      bloodPressure: '150/92',
      systolicBP: 150,
      diastolicBP: 92,
      spO2: 84,
      temperature: 38.2,
      respiratoryRate: 30,
      bloodGlucose: 155,
      measuredAt: '5 mins ago',
    },
    clinicalRecords: [],
    reports: [],
    latestAssessment: {
      id: 'AI-906',
      patientId: 'P006',
      patientName: 'Deepa Nair',
      riskScore: 89,
      priority: 'CRITICAL',
      assessedAt: '2026-09-12 14:00',
      riskFactors: [
        'Severe Desaturation (SpO2 84%)',
        'Severe Tachypnea (30 breaths/min)',
        'Cyanosis & Silent Chest Sign',
      ],
      explanation: 'Severe status asthmaticus presenting with respiratory exhaustion. Immediate airway stabilization and doctor assignment required.',
      recommendedActions: [
        'Immediate doctor assignment & emergency intervention',
        'Continuous High-Flow BiPAP / Oxygen Support',
        'Immediate IV Corticosteroids & Bronchodilators',
      ],
      status: 'Active',
    },
    assignedDoctor: undefined,
    assignedDoctorId: undefined,
    treatmentStatus: 'WAITING',
    treatmentHistory: [],
    waitingTimeMinutes: 8,
    registeredAt: '2026-09-12 13:55',
  },
];
